version: "3.2"
services:
  hugo:
    image: klakegg/hugo:0.101.0
    command: >
      server 
        --environment ${HUGO_ENVIRONMENT}
        --appendPort=false
        --disableFastRender
        --disableLiveReload
        --port ${HUGO_PORT}
        --baseURL ${HUGO_BASEURL}
    volumes:
      - "${PWD}:/src"
    ports:
      - "${HUGO_PORT}:${HUGO_PORT}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
